"""Assessment specifications for CMPSC 480 Weeks 2-5 and Quizzes 1-2."""


def part(label, points, question, answer):
    return {"label": label, "points": points, "question": question, "answer": answer}


def problem(pid, title, points, prompt, deliverable, grading, parts, **extra):
    value = {
        "id": pid,
        "title": title,
        "points": points,
        "prompt": prompt,
        "deliverable": deliverable,
        "grading": grading,
        "parts": parts,
    }
    value.update(extra)
    return value


COMMON_REQUIREMENTS = [
    "Use Python 3.11 and NumPy only unless the prompt explicitly permits another package.",
    "Preserve the published interfaces and make all tie-breaking deterministic.",
    "State assumptions, validate inputs, and handle empty, terminal, and unreachable cases.",
    "Include focused tests whose names explain the defect each test would expose.",
    "Report measured evidence; do not replace experimental results with unsupported claims.",
]


SPECS = {
    "week_02_assignment": {
        "title": "Week 2 Assignment: A Unified Search Engine",
        "subtitle": "BFS, DFS, UCS, and A-star behind one tested graph-search core",
        "short_title": "Week 2 Assignment",
        "overview": "Implement and compare four search strategies while preserving one domain contract.",
        "coverage": "Weeks 1-2: problem formulation, graph search, costs, heuristics, and testing",
        "duration": "6-8 hours",
        "submission": "Repository plus PDF report",
        "total_points": 10,
        "objectives": [
            "Implement BFS, DFS, UCS, and A-star through a shared frontier abstraction.",
            "Use state keys and best-cost bookkeeping correctly in cyclic graphs.",
            "Justify admissibility and consistency of a grid heuristic.",
            "Compare strategies with solution-cost and search-effort measurements.",
            "Design edge-case tests that distinguish algorithmic guarantees.",
        ],
        "requirements": COMMON_REQUIREMENTS,
        "problems": [
            problem(
                1,
                "Shared search contract",
                2,
                "Define the problem, node, result, and frontier interfaces before implementing a strategy.",
                "Typed interfaces, validation, and a deterministic result schema.",
                "Interfaces separate state from node metadata and reject invalid costs.",
                [
                    part("a", 1, "Specify the required fields and methods of SearchProblem, Node, and SearchResult.", "SearchProblem exposes initial_state, is_goal, successors, and step cost. Node stores state, parent, action, depth, and accumulated cost. SearchResult reports path, cost, generated count, expanded count, and maximum frontier size."),
                    part("b", 1, "Define an immutable state-key policy and list two input validation rules.", "State keys must be hashable, stable, and based only on the world configuration. Validation must reject nonpositive UCS/A-star step costs and malformed successors; deterministic successor order must be documented."),
                ],
            ),
            problem(
                2,
                "BFS and DFS policies",
                2,
                "Implement breadth-first and depth-first graph search by changing only frontier removal order.",
                "Working FIFO and LIFO policies plus trace tests.",
                "Correct ordering, cycle termination, and path reconstruction.",
                [
                    part("a", 1, "Explain the exact frontier and explored-set behavior for BFS and DFS.", "BFS removes the oldest frontier entry and DFS removes the newest. A state is expanded at most once; parent links remain on nodes so the returned action sequence can be reconstructed."),
                    part("b", 1, "Give one test that separates BFS from DFS and one cyclic test that proves termination.", "A branching graph with shallow and deep goals exposes FIFO versus LIFO behavior. A two-node cycle with an unreachable goal must terminate with failure and finite expansion counts."),
                ],
            ),
            problem(
                3,
                "UCS and A-star",
                4,
                "Add cost-sensitive search and demonstrate that cheaper rediscovery replaces a worse frontier path.",
                "Priority-frontier implementation, heuristic, and correctness traces.",
                "Correct priorities, updates, goal timing, and heuristic reasoning.",
                [
                    part("a", 1, "State the priority used by UCS and A-star and specify when the goal test occurs.", "UCS orders by g and A-star by f=g+h. The goal is accepted when removed at minimum priority, not merely when generated."),
                    part("b", 1, "Trace a graph where A is first reached with cost 5 and later through B with cost 2.", "The best-cost map changes best[A] from 5 to 2. The stale cost-5 entry is skipped when removed, or it is decreased in a frontier supporting decrease-key."),
                    part("c", 1, "Define Manhattan distance for a four-neighbor unit-cost grid and prove admissibility.", "The heuristic is the absolute row difference plus absolute column difference. Every legal move changes this quantity by at most one, so any path needs at least that many moves; therefore it never exceeds optimal remaining cost."),
                    part("d", 1, "Prove consistency of Manhattan distance for each legal edge.", "For adjacent states n and n-prime, the triangle inequality gives h(n) at most 1 plus h(n-prime). Since each step costs one, h(n) at most c(n,n-prime)+h(n-prime), which is consistency."),
                ],
            ),
            problem(
                4,
                "Experiments and defensive tests",
                2,
                "Evaluate all strategies on common instances and explain differences using theory.",
                "Reproducible result table, tests, and concise analysis.",
                "Evidence includes costs, effort, edge cases, and justified conclusions.",
                [
                    part("a", 1, "Report path cost, generated nodes, expanded nodes, and maximum frontier for at least three maps.", "A full-credit table identifies the map and deterministic tie rule, reports all four metrics for every strategy, and checks returned paths independently."),
                    part("b", 1, "Include no-solution, single-cell, cheaper-rediscovery, and scale tests and state the bug each detects.", "No-solution checks graceful failure; single-cell checks immediate success; cheaper rediscovery checks cost updates; scale checks asymptotic memory and performance without changing correctness."),
                ],
            ),
        ],
        "edge_cases": [
            "The initial state already satisfies the goal test.",
            "The graph contains a reachable cycle but no goal.",
            "A state is rediscovered through a strictly cheaper path.",
            "Two frontier entries have equal priority and require deterministic ties.",
            "The heuristic returns zero everywhere, reducing A-star to UCS.",
        ],
        "edge_solutions": [
            "Return an empty action path with cost zero and no unnecessary expansion.",
            "The explored or best-cost map prevents infinite repetition and returns explicit failure.",
            "Replace the recorded best cost and ignore any stale expensive frontier entry.",
            "Use a monotonic insertion counter after the primary priority.",
            "A-star with h=0 must match UCS solution cost and expansion behavior modulo ties.",
        ],
        "submission_steps": [
            "Submit source, tests, and a README containing the exact test command.",
            "Include a PDF result table and a short explanation of every surprising measurement.",
            "Tag the final commit and ensure a clean clone reproduces the tests.",
        ],
        "reflection_length": "150-200 words",
        "reflection": "Identify one implementation choice that affected a theoretical guarantee. Cite a failing or passing test and explain what you changed.",
        "reflection_answer": "A strong reflection names a concrete rule, such as testing goals on removal or updating a cheaper duplicate, connects it to an optimality assumption, and cites reproducible test evidence.",
    },
    "week_03_assignment": {
        "title": "Week 3 Module Project A: Search and Adversarial Agents",
        "subtitle": "Integrating pathfinding with minimax, alpha-beta pruning, and evaluation",
        "short_title": "Module Project A",
        "overview": "Build a deterministic agent that plans paths and chooses actions against an opponent.",
        "coverage": "Weeks 1-3: search formulation, A-star, minimax, alpha-beta, and evaluation",
        "duration": "10-14 hours",
        "submission": "Repository, tests, and engineering report",
        "total_points": 20,
        "objectives": [
            "Reuse a stable search core for deterministic pathfinding.",
            "Implement depth-limited minimax and alpha-beta pruning.",
            "Design a state evaluation function with explicit feature semantics.",
            "Keep planning and adversarial reasoning behind separate interfaces.",
            "Measure correctness, pruning effectiveness, and decision quality.",
        ],
        "requirements": COMMON_REQUIREMENTS + [
            "Do not mutate game states shared by sibling branches.",
            "Return a legal action for every nonterminal state with at least one legal move.",
        ],
        "problems": [
            problem(
                1,
                "Architecture and pathfinding",
                4,
                "Define component boundaries and integrate BFS, DFS, and A-star pathfinding.",
                "Architecture diagram, interfaces, and pathfinding tests.",
                "Clean separation, deterministic behavior, and correct path costs.",
                [
                    part("a", 1, "Draw the boundary among game state, search problem, pathfinder, and adversarial agent.", "The state owns rules and legal transitions; the problem adapts a state to pathfinding; the pathfinder returns paths and metrics; the agent consumes immutable successor states and returns one action."),
                    part("b", 2, "Implement BFS, DFS, and A-star behind one pathfinding interface.", "The methods share expansion and reconstruction logic, differ only in frontier priority, terminate on cycles, and return explicit failure on unreachable goals."),
                    part("c", 1, "Demonstrate path validity and deterministic tie-breaking.", "Every adjacent state-action pair is revalidated by the domain. Equal priorities use a documented stable rule, and repeated runs produce identical paths."),
                ],
            ),
            problem(
                2,
                "A-star heuristic",
                3,
                "Design, justify, and test a domain-specific heuristic.",
                "Formula, proof sketch, and comparison against h=0.",
                "Heuristic is safe, informative, and experimentally supported.",
                [
                    part("a", 1, "Define the heuristic and its units.", "A valid answer uses a lower bound expressed in path-cost units, such as obstacle-ignoring Manhattan distance times the minimum legal step cost."),
                    part("b", 1, "Give an admissibility or consistency proof sketch.", "Relaxing obstacles can only shorten the route, so the relaxed optimal cost is no greater than the true cost. For local consistency, show h(n) no greater than edge cost plus h of each successor."),
                    part("c", 1, "Compare A-star with h=0 on at least three maps.", "Both configurations return equal optimal costs. The informative heuristic should usually expand no more nodes; exceptions caused by ties are explained."),
                ],
            ),
            problem(
                3,
                "Minimax decision engine",
                5,
                "Implement deterministic, depth-limited minimax with correct terminal semantics.",
                "Minimax implementation, hand trace, and unit tests.",
                "Backups, player alternation, depth limits, and legal actions are correct.",
                [
                    part("a", 2, "Write minimax pseudocode with MAX, MIN, terminal, and cutoff cases.", "Terminal utility is returned before a heuristic cutoff. MAX takes the largest child value, MIN takes the smallest, and the root returns the action paired with the best value."),
                    part("b", 2, "Trace a depth-two tree with at least two actions per internal node.", "The solution labels leaf utilities, computes each MIN value, then chooses the maximum at the root. All backed-up values and the selected action are shown."),
                    part("c", 1, "Explain how depth is counted and how ties are broken.", "Depth is defined consistently as plies from the root or remaining plies. A stable legal-action order chooses the first tied optimum so tests remain reproducible."),
                ],
            ),
            problem(
                4,
                "Alpha-beta and evaluation",
                5,
                "Add pruning without changing minimax values and construct a defensible cutoff evaluation.",
                "Alpha-beta implementation, evaluation ablation, and pruning metrics.",
                "Bounds are updated correctly; evaluation features and evidence are sound.",
                [
                    part("a", 2, "State the alpha and beta invariants and the pruning condition.", "Alpha is MAX's best guaranteed lower bound; beta is MIN's best guaranteed upper bound. A branch can be pruned when alpha is at least beta because it cannot change the ancestor decision."),
                    part("b", 1, "Verify equality with plain minimax across generated small trees.", "For every tested tree and depth, minimax and alpha-beta return the same value and a tie-equivalent action. The test varies utilities and successor order."),
                    part("c", 1, "Define an evaluation function as a weighted feature sum.", "Features have stated perspective and scale, for example score difference, distance-to-objective, mobility, and threat. Positive weights favor MAX and terminal states bypass the heuristic."),
                    part("d", 1, "Measure the effect of ordering and evaluation features.", "The report compares expanded nodes under good and bad ordering and performs at least one feature ablation tied to decision quality."),
                ],
            ),
            problem(
                5,
                "Integration and evidence",
                3,
                "Deliver an end-to-end agent and explain failures with reproducible evidence.",
                "Integrated demo, adversarial tests, and concise report.",
                "End-to-end correctness, boundary cases, and technical interpretation.",
                [
                    part("a", 1, "Run an end-to-end scenario that uses both pathfinding and adversarial choice.", "The scenario makes the component handoff visible, validates every returned action, and records the chosen path and game decision."),
                    part("b", 1, "Test terminal roots, no legal actions, repeated states, and a narrow pruning window.", "Each test states expected output and detects a distinct semantic, mutation, cycle, or bound-update defect."),
                    part("c", 1, "Report nodes expanded, prune count, decision value, and runtime.", "Measurements use the same states, depth, hardware context, and tie order; conclusions distinguish correctness from speed."),
                ],
            ),
        ],
        "edge_cases": [
            "The game is terminal at the root.",
            "A nonterminal state has no legal actions because of a domain defect.",
            "Different paths reach the same immutable state.",
            "All root actions have equal backed-up value.",
            "Alpha equals beta exactly after an update.",
        ],
        "edge_solutions": [
            "Return terminal utility and no action without calling the evaluator.",
            "Fail loudly or apply a documented pass rule; never return an arbitrary illegal action.",
            "Pathfinding deduplicates state keys; adversarial search avoids unsafe transposition reuse unless depth and bounds are encoded.",
            "Choose the first action in stable domain order.",
            "Pruning is safe when alpha is greater than or equal to beta.",
        ],
        "submission_steps": [
            "Submit the repository with modules, tests, and a reproducible demo command.",
            "Include a report with architecture, heuristic argument, evaluation features, and result tables.",
            "Provide a tagged final commit and exclude generated caches and credentials.",
        ],
        "reflection_length": "200-250 words",
        "reflection": "Explain one integration defect that looked like an algorithm defect. Describe the boundary contract, the diagnostic evidence, and the final repair.",
        "reflection_answer": "A strong response distinguishes pathfinding from game-state semantics, cites a minimal reproducer, identifies which contract was violated, and reports the regression test that now protects it.",
    },
    "week_04_assignment": {
        "title": "Week 4 Assignment: Planning in a Stochastic Gridworld",
        "subtitle": "MDP modeling, value iteration, policy iteration, and verification",
        "short_title": "Week 4 Assignment",
        "overview": "Model stochastic transitions precisely and solve the same MDP with two dynamic-programming methods.",
        "coverage": "Week 4: MDPs, Bellman backups, value iteration, and policy iteration",
        "duration": "6-8 hours",
        "submission": "Repository plus experiment memo",
        "total_points": 10,
        "objectives": [
            "Encode a finite MDP with normalized transition distributions.",
            "Implement terminal-aware Bellman backups.",
            "Run value iteration to a documented tolerance.",
            "Alternate policy evaluation and improvement correctly.",
            "Cross-check two solvers and reason about edge cases.",
        ],
        "requirements": COMMON_REQUIREMENTS,
        "problems": [
            problem(
                1, "MDP model", 2,
                "Represent grid states, walls, terminal rewards, legal actions, and 80/10/10 stochastic motion.",
                "Validated transition and reward functions.",
                "Probabilities normalize and terminal/wall semantics are explicit.",
                [
                    part("a", 1, "Define S, A, P, R, gamma, initial state, walls, and terminal states.", "States are legal grid cells; actions are cardinal moves; intended motion has probability 0.8 and perpendicular slips 0.1 each. Blocked motion stays in place. Rewards and terminal semantics are stated, with gamma in [0,1)."),
                    part("b", 1, "Write validation tests for every state-action transition distribution.", "For each legal nonterminal pair, successor probabilities are nonnegative and sum to one within tolerance; all successors are legal states. Terminal states expose no actions or a documented absorbing convention."),
                ],
            ),
            problem(
                2, "Value iteration", 3,
                "Implement synchronous Bellman optimality backups and a convergence test.",
                "Value iteration, policy extraction, and residual trace.",
                "Backups, convergence, and terminal handling are correct.",
                [
                    part("a", 1, "Write the Bellman optimality backup used for each nonterminal state.", "V_new(s) is the maximum over actions of the sum over successors of P(s-prime|s,a) times [R(s,a,s-prime)+gamma V_old(s-prime)]. Terminal values follow the declared reward convention."),
                    part("b", 1, "Use a copy of the previous value vector and stop when the maximum residual is below tolerance.", "Synchronous updates read only V_old. The residual is max_s absolute(V_new(s)-V_old(s)); iteration count has a safety bound and tolerance is positive."),
                    part("c", 1, "Extract a deterministic greedy policy and report values for designated cells.", "Each action is scored with the final Bellman lookahead; stable action order resolves ties. Reported cells match an independently computed oracle within tolerance."),
                ],
            ),
            problem(
                3, "Policy iteration", 3,
                "Alternate policy evaluation with greedy policy improvement.",
                "Policy iteration and comparison with value iteration.",
                "Evaluation/improvement loops and stopping rule are sound.",
                [
                    part("a", 1, "Describe iterative policy evaluation for a fixed policy.", "Repeatedly apply the Bellman expectation backup using only the current policy action until the evaluation residual is below tolerance."),
                    part("b", 1, "Implement greedy improvement and state the stability condition.", "For every nonterminal state choose an action maximizing one-step lookahead under the evaluated values. Stop when no chosen action changes under deterministic ties."),
                    part("c", 1, "Compare the final policy and values with value iteration.", "Optimal values agree within a declared numerical tolerance, and policies are equal or choose actions with equal optimal action value."),
                ],
            ),
            problem(
                4, "Validation and analysis", 2,
                "Use analytic and metamorphic checks rather than trusting one implementation.",
                "Tests and a concise result table.",
                "Tests expose modeling errors and conclusions follow evidence.",
                [
                    part("a", 1, "Test gamma=0, a one-state terminal MDP, blocked slips, and a reward perturbation.", "At gamma=0 only immediate expected reward matters. The terminal case is stable. Blocked slips accumulate probability on staying put. Increasing one terminal reward should not reduce optimal value in reachable states."),
                    part("b", 1, "Explain how gamma and slip probability change the policy in two experiments.", "The answer compares controlled runs, reports values and actions, and links larger gamma to future rewards while larger slip can favor safer routes."),
                ],
            ),
        ],
        "edge_cases": ["Initial state is terminal.", "A slip hits a wall or boundary.", "Two actions have equal value.", "Gamma equals zero.", "Tolerance is nonpositive."],
        "edge_solutions": ["Return the terminal convention immediately.", "Merge that probability into the stay-put successor.", "Use documented stable action order.", "Backups reduce to immediate expected reward.", "Reject the configuration before iteration."],
        "submission_steps": ["Submit source, tests, and exact run commands.", "Include residual and policy-comparison tables.", "State reward and terminal conventions in the README."],
        "reflection_length": "150-200 words",
        "reflection": "Describe one modeling choice whose effect was larger than an algorithmic optimization. Support the claim with a controlled comparison.",
        "reflection_answer": "A strong answer isolates a transition, reward, terminal, gamma, or slip convention, reports before-and-after values or policies, and explains why both solvers changed consistently.",
    },
    "week_05_assignment": {
        "title": "Week 5 Assignment: Tabular Q-Learning",
        "subtitle": "A tested model-free agent with controlled exploration and oracle comparison",
        "short_title": "Week 5 Assignment",
        "overview": "Train a tabular Q-learning agent and evaluate learning behavior against a planning oracle.",
        "coverage": "Week 5: TD learning, exploration, terminal targets, and empirical evaluation",
        "duration": "6-8 hours",
        "submission": "Repository, learning curves, and report",
        "total_points": 10,
        "objectives": [
            "Separate environment dynamics from agent state.",
            "Implement epsilon-greedy action selection with deterministic evaluation.",
            "Apply the terminal-aware Q-learning update.",
            "Run reproducible training and evaluation phases.",
            "Compare a learned policy with value-iteration ground truth.",
        ],
        "requirements": COMMON_REQUIREMENTS + ["Seed every source of randomness used in reported experiments."],
        "problems": [
            problem(
                1, "Agent and exploration contract", 2,
                "Implement a Q-table agent without embedding environment transition logic.",
                "Agent API, epsilon schedule, and action-selection tests.",
                "Separation, legal actions, exploration probabilities, and ties are correct.",
                [
                    part("a", 1, "Define observe, select_action, update, and evaluate-mode behavior.", "The agent receives transitions from the environment, stores Q values keyed by state-action, selects only legal actions, updates from observations, and uses epsilon zero during evaluation."),
                    part("b", 1, "Specify epsilon-greedy selection and a bounded decay schedule.", "With probability epsilon choose uniformly among legal actions; otherwise choose a stable argmax. Decay is applied at a documented cadence and clipped to epsilon_min."),
                ],
            ),
            problem(
                2, "Q-learning update", 3,
                "Implement and validate the off-policy temporal-difference update.",
                "Update function and hand-computed unit tests.",
                "TD target, terminal mask, and in-place assignment are correct.",
                [
                    part("a", 1, "State the update and define the TD error.", "The target is r plus gamma times max over next legal actions Q(s-prime,a-prime) for nonterminal transitions. Delta is target minus Q(s,a), and Q(s,a) increases by alpha times delta."),
                    part("b", 1, "Compute one update for Q=2, r=1, gamma=0.9, max next Q=4, and alpha=0.5.", "The target is 1+0.9*4=4.6; delta is 2.6; the updated value is 2+0.5*2.6=3.3."),
                    part("c", 1, "Explain and test terminal handling.", "For done=True the target is r only; no next-state maximum is used. A test gives a very large next Q value and confirms it does not change the terminal update."),
                ],
            ),
            problem(
                3, "Training protocol", 2,
                "Build a reproducible episodic training loop with safety limits.",
                "Training loop, seeds, and logged metrics.",
                "Episodes terminate safely and training/evaluation are distinct.",
                [
                    part("a", 1, "Describe reset, interaction, update, and episode termination order.", "Reset returns the initial state; each step selects, executes, records reward and done, updates once, and advances state. The loop ends on done or a maximum-step truncation."),
                    part("b", 1, "Log return, episode length, epsilon, and moving-average return.", "Metrics use consistent windows and distinguish truncation from environment termination. Seeds and hyperparameters are recorded with the run."),
                ],
            ),
            problem(
                4, "Evaluation and tests", 3,
                "Measure policy quality and diagnose sensitivity to exploration and rewards.",
                "Oracle comparison, ablation, and edge-case tests.",
                "Metrics are unbiased, controlled, and interpreted correctly.",
                [
                    part("a", 1, "Evaluate the greedy policy without learning or exploration.", "Set epsilon to zero, freeze Q values, run independent seeded episodes, and report mean return, success rate, and confidence or variability."),
                    part("b", 1, "Compare greedy actions or returns with a value-iteration oracle.", "Map both policies to the same MDP semantics. Count exact or tie-equivalent action agreement and explain differences caused by incomplete visitation or stochastic estimates."),
                    part("c", 1, "Run one controlled hyperparameter ablation and cover sparse-reward and unseen-state cases.", "Vary only alpha, epsilon schedule, or gamma. Report curves and explain bias/noise effects. Unseen states start from a documented default; sparse rewards do not cause crashes or false convergence claims."),
                ],
            ),
        ],
        "edge_cases": ["No legal actions are returned.", "The transition is terminal.", "All action values tie.", "A state has never been visited.", "An episode reaches the safety step limit."],
        "edge_solutions": ["Treat it as terminal or raise a domain-contract error.", "Use target equal to the immediate reward.", "Choose deterministically in evaluation and uniformly only in exploration.", "Use the declared initialization value for every legal action.", "Record truncation separately and stop without a synthetic terminal bootstrap."],
        "submission_steps": ["Submit source, tests, seeds, and hyperparameters.", "Include learning curves plus a compact oracle-comparison table.", "Document the exact command that reproduces the reported run."],
        "reflection_length": "150-200 words",
        "reflection": "Explain one gap between a learned policy and the planning oracle. Distinguish modeling mismatch from sampling or optimization error.",
        "reflection_answer": "A strong response verifies shared MDP semantics first, then uses visitation counts, TD error, or repeated-run evidence to attribute the remaining gap to exploration, finite data, or hyperparameters.",
    },
    "quiz_01": {
        "title": "Quiz 1: Agents and Search",
        "subtitle": "Weeks 1-2",
        "short_title": "Quiz 1",
        "overview": "Demonstrate concise reasoning about agent models and classical search guarantees.",
        "coverage": "Weeks 1-2",
        "duration": "30 minutes",
        "submission": "Individual PDF",
        "total_points": 20,
        "objectives": ["Apply PEAS and search formulation.", "Trace frontier order.", "Compare guarantees.", "Reason about admissible heuristics."],
        "requirements": ["Work independently.", "Show intermediate frontier or arithmetic steps.", "State every assumption used for a guarantee.", "No electronic communication."],
        "problems": [
            problem(1, "Agent formulation", 4, "Analyze a warehouse-routing agent.", "Written responses.", "PEAS and rationality are precise.", [
                part("a", 2, "Give one element for each PEAS component.", "Performance: timely collision-free deliveries; environment: aisles, shelves, people, and stations; actuators: wheel and lift commands; sensors: lidar, odometry, and task messages."),
                part("b", 2, "Explain why rational does not mean omniscient.", "A rational agent maximizes expected performance from its percept history and knowledge. It can still fail because observations and outcomes are uncertain; omniscience would require knowing actual future consequences."),
            ]),
            problem(2, "BFS and DFS trace", 4, "Successors are generated alphabetically. S connects to A and B; A to G; B to C; C to G.", "Frontier trace and returned paths.", "FIFO/LIFO order and trace are correct.", [
                part("a", 2, "Trace BFS until a goal is removed.", "FIFO trace: [S], then [A,B], then [B,G], then [G,C], then remove G. The returned path is S-A-G."),
                part("b", 2, "Trace DFS when successors are pushed in alphabetical order.", "After pushing A then B, LIFO removes B, then C, then G; it can return S-B-C-G. A different documented push convention earns credit if traced consistently."),
            ]),
            problem(3, "Cost-sensitive search", 6, "Two routes reach a goal: S-A-G costs 5+1, and S-B-C-G costs 1+1+1.", "Algorithm choice and cost trace.", "Depth/cost distinction and UCS update are correct.", [
                part("a", 2, "Which route can BFS return, and why is that not a minimum-cost guarantee?", "BFS returns the depth-two route S-A-G with cost 6, because it minimizes depth under FIFO order rather than nonuniform path cost."),
                part("b", 2, "Trace UCS priorities until the goal is removed.", "UCS removes S(0), B(1), C(2), G(3), and returns S-B-C-G with cost 3."),
                part("c", 2, "State conditions under which UCS is complete and optimal.", "With finite branching and step costs bounded below by a positive epsilon, UCS is complete and removes an optimal goal first."),
            ]),
            problem(4, "A-star heuristic", 6, "A four-neighbor grid uses unit costs and Manhattan distance.", "Proof sketch and comparison.", "Admissibility, consistency, and f values are correct.", [
                part("a", 2, "Define f, g, and h in A-star.", "g is accumulated path cost, h estimates optimal remaining cost, and f=g+h orders the frontier."),
                part("b", 2, "Prove Manhattan distance is consistent.", "A legal step costs one and changes Manhattan distance by at most one, hence h(n) is at most 1+h(n-prime) for every edge."),
                part("c", 2, "If two nodes have (g,h)=(4,3) and (5,1), which is removed first?", "Their f values are 7 and 6, so the second node is removed first, subject only to stale-entry handling and ties."),
            ]),
        ],
        "edge_cases": ["A start state is already a goal.", "A graph contains a cycle.", "Two A-star nodes have equal f."],
        "edge_solutions": ["Return the empty path.", "Use graph-search bookkeeping to terminate.", "Apply the stated deterministic secondary key."],
        "submission_steps": ["Write your name and assumptions.", "Show work for traces and arithmetic.", "Submit only the question-response PDF."],
        "reflection_length": "one sentence",
        "reflection": "Name the assumption most often omitted when stating a search guarantee.",
        "reflection_answer": "A suitable answer identifies finite branching, uniform costs for BFS optimality, or a positive lower bound on step cost for UCS, with the relevant algorithm named.",
    },
    "quiz_02": {
        "title": "Quiz 2: Adversarial and Sequential Decision Making",
        "subtitle": "Weeks 3-5",
        "short_title": "Quiz 2",
        "overview": "Trace adversarial backups, solve a Bellman step, and apply a Q-learning update.",
        "coverage": "Weeks 3-5",
        "duration": "35 minutes",
        "submission": "Individual PDF",
        "total_points": 20,
        "objectives": ["Trace minimax and pruning.", "Interpret an MDP.", "Perform Bellman and Q-learning updates.", "Distinguish planning from learning."],
        "requirements": ["Work independently.", "Show backed-up values and arithmetic.", "State terminal conventions.", "No electronic communication."],
        "problems": [
            problem(1, "Minimax and alpha-beta", 6, "A MAX root has MIN children A and B. A has leaves 3 and 5; B has leaves 2 and 9.", "Tree trace.", "Backups and pruning reasoning are correct.", [
                part("a", 2, "Compute the minimax value and selected branch.", "MIN(A)=3 and MIN(B)=2, so MAX chooses A with value 3."),
                part("b", 2, "Search A first. After B's first leaf 2, can B's second leaf be pruned?", "Yes. The root alpha is 3 after A; B's beta becomes 2, so alpha is at least beta and the remaining B child cannot improve MAX's decision."),
                part("c", 2, "Does pruning change the backed-up value? Explain.", "No. Alpha-beta removes branches proven irrelevant to the root decision and returns the same minimax value under exact arithmetic."),
            ]),
            problem(2, "MDP backup", 6, "From state s, action a reaches terminal +5 with probability 0.8 and state t with probability 0.2. The immediate reward is 0, gamma=0.9, and V(t)=2.", "Expected-return calculation.", "Probability, reward, and discount are combined correctly.", [
                part("a", 2, "Write the Bellman action-value expression.", "Q(s,a)=0.8[0+0.9*5]+0.2[0+0.9*2] under the convention that terminal state's listed value is 5."),
                part("b", 2, "Compute Q(s,a).", "The result is 0.8*4.5+0.2*1.8=3.6+0.36=3.96."),
                part("c", 2, "Explain what value iteration maximizes.", "For every nonterminal state it computes this expected return for each legal action and sets the new value to the maximum."),
            ]),
            problem(3, "Q-learning", 4, "Q(s,a)=1, reward=2, max next Q=3, gamma=0.5, and alpha=0.25.", "One numerical update.", "Target, TD error, and update are correct.", [
                part("a", 2, "Compute the nonterminal target and TD error.", "Target=2+0.5*3=3.5 and delta=3.5-1=2.5."),
                part("b", 2, "Compute the updated Q value and state the terminal change.", "New Q=1+0.25*2.5=1.625. If terminal, target is reward 2 and new Q is 1.25."),
            ]),
            problem(4, "Planning versus learning", 4, "Compare value iteration and Q-learning for the same gridworld.", "Short explanation.", "Model, data, and convergence distinctions are precise.", [
                part("a", 2, "What information does each method require?", "Value iteration requires an explicit transition and reward model. Q-learning can learn from sampled transitions without knowing those probabilities."),
                part("b", 2, "Why must a Q-learning evaluation run use epsilon zero?", "Exploration intentionally chooses suboptimal actions, so leaving epsilon positive confounds learned policy quality with exploration noise."),
            ]),
        ],
        "edge_cases": ["A minimax root is terminal.", "An MDP action has probabilities that do not sum to one.", "A Q-learning transition is terminal."],
        "edge_solutions": ["Return utility without expanding.", "Reject or normalize only under an explicit data-cleaning policy.", "Remove the bootstrap term."],
        "submission_steps": ["Show every backup and update.", "State any convention needed for terminal reward.", "Submit only the completed response PDF."],
        "reflection_length": "one sentence",
        "reflection": "State one reason a learned policy can differ from a planning oracle.",
        "reflection_answer": "Valid reasons include finite exploration, noisy estimates, hyperparameter effects, or a mismatch in transition, reward, or terminal semantics.",
    },
}
